import { Hero } from "./types";

export const heroes: Hero[] = [
  { name: "Abrams" },
  { name: "Apollo" },
  { name: "Bebop" },
  { name: "Billy" },
  { name: "Calico" },
  { name: "Celeste" },
  { name: "Drifter" },
  { name: "Dynamo" },
  { name: "Graves" },
  { name: "Grey Talon" },
  { name: "Haze" },
  { name: "Holliday" },
  { name: "Infernus" },
  { name: "Ivy" },
  { name: "Kelvin" },
  { name: "Lady Geist" },
  { name: "Lash" },
  { name: "McGinnis" },
  { name: "Mina" },
  { name: "Mirage" },
  { name: "Mo & Krill" },
  { name: "Paige" },
  { name: "Paradox" },
  { name: "Pocket" },
  { name: "Rem" },
  { name: "Seven" },
  { name: "Shiv" },
  { name: "Silver" },
  { name: "Sinclair" },
  { name: "The Doorman" },
  { name: "Venator" },
  { name: "Victor" },
  { name: "Vindicta" },
  { name: "Viscous" },
  { name: "Vyper" },
  { name: "Warden" },
  { name: "Wraith" },
  { name: "Yamato" },
] as const;
